.. _annuity_om:

Annual operation, maintenance and dispatch expenses (annuity_om)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Annuity of the operation, maintenance and dispatch costs of the asset or energy system, i.e. ballpark number of the annual expenses for asset or system operation.
:Type: Numeric
:Unit: currency/a
:Valid Interval: >=0
:Related indicators: :ref:`annuity_total` | :ref:`costs_om_total`

