.. _attributed_costs:

Costs attributed to a specific sector (attributed_costs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Costs attributed to supplying the demand of a specific sector, based on the :ref:`net present costs (NPC) <costs_total>` of the energy system and the share of the sector demand compared to the overall system demand.
:Type: Numeric
:Unit: currency
:Valid Interval: >=0
:Related indicators: :ref:`costs_total`

