.. _costs_total:

Net Present Costs (NPC) (costs_total)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Net present costs of the system for the whole project duration, includes all operation, maintainance and dispatch costs as well as the investment costs (including replacements). Applied to a single asset, the costs can also be called present costs of the asset.
:Type: Numeric
:Unit: currency
:Valid Interval: >=0
:Related indicators: :ref:`costs_cost_om` | :ref:`costs_dispatch` | :ref:`costs_investment_over_lifetime` | :ref:`costs_om_total` | :ref:`costs_upfront_in_year_zero`

