.. _costs_om_total:

Operation, maintenance and dispatch costs (costs_om_total)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Costs for annual operation and maintenance costs as well as dispatch of all assets of the energy system, for the whole project duration.
:Type: Numeric
:Unit: currency
:Valid Interval: >=0
:Related indicators: :ref:`costs_cost_om` | :ref:`costs_dispatch` | :ref:`costs_investment_over_lifetime` | :ref:`costs_total` | :ref:`costs_upfront_in_year_zero`

