.. _costs_investment_over_lifetime:

Investment costs (costs_investment_over_lifetime)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Investment costs over the whole project lifetime, including all replacement costs.
:Type: Numeric
:Unit: currency
:Valid Interval: >=0
:Related indicators: :ref:`costs_cost_om` | :ref:`costs_dispatch` | :ref:`costs_om_total` | :ref:`costs_total` | :ref:`costs_upfront_in_year_zero` | :ref:`replacement_costs_during_project_lifetime`

