.. _costs_upfront_in_year_zero:

Upfront investment costs (costs_upfront_in_year_zero)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: The costs which will have to be paid upfront when project begins, ie. In year 0. These are the investment and fix project costs into the chosen  configuration.
:Type: Numeric
:Unit: currency
:Valid Interval: >=0
:Related indicators: :ref:`costs_cost_om` | :ref:`costs_dispatch` | :ref:`costs_investment_over_lifetime` | :ref:`costs_om_total` | :ref:`costs_total`

