.. _costs_dispatch:

Dispatch costs (costs_dispatch)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Dispatch costs over the whole project lifetime including all expenditures that depend on the dispatch of assets (e.g. fuel costs, electricity consumption from the external grid, costs for operation and maintainance that depend on the throughput of an asset)
:Type: Numeric
:Unit: currency
:Valid Interval: >=0
:Related indicators: :ref:`costs_cost_om` | :ref:`costs_investment_over_lifetime` | :ref:`costs_om_total` | :ref:`costs_total` | :ref:`costs_upfront_in_year_zero`

