.. _costs_cost_om:

Operation and maintenance costs (costs_cost_om)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Costs for fix annual operation and maintenance costs over the whole project lifetime, which do not depend on the assets dispatch but solely on installed capacity. An example would be the maintenance costs for cleaning the installed PV capacity.
:Type: Numeric
:Unit: currency
:Valid Interval: >=0
:Related indicators: :ref:`costs_dispatch` | :ref:`costs_investment_over_lifetime` | :ref:`costs_om_total` | :ref:`costs_total` | :ref:`costs_upfront_in_year_zero`

