.. _degree_of_autonomy:

Degree of Autonomy (degree_of_autonomy)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: A degree of autonomy close to zero shows high dependence on the energy provider, while a degree of autonomy of 1 represents an autonomous or net-energy system and a degree of autonomy higher 1 a surplus-energy system.
:Type: Numeric
:Unit: Factor
:Valid Interval: [0,1]
:Related indicators: :ref:`total_demand`

