.. _levelized_cost_of_energy_of_asset:

Levelized cost of throughput (levelized_cost_of_energy_of_asset)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Cost per kWh throughput through an asset, based on the assets costs during the project lifetime as well as the total throughput through the asset in the project lifetime. For generation assets, equivalent to the levelized cost of generation.
:Type: Numeric
:Unit: currency/kWh
:Valid Interval: >=0
:Related indicators: :ref:`annuity_total` | :ref:`annual_total_flow`

