.. _levelized_costs_of_electricity_equivalent:

Levelized costs of electricity equivalent (levelized_costs_of_electricity_equivalent)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Levelized cost of energy of the sector-coupled energy system, calculated from the systems annuity and the total system demand in electricity equivalent.
:Type: Numeric
:Unit: currency/kWheleq
:Valid Interval: >=0
:Related indicators: :ref:`costs_total` | :ref:`total_demand`

