Technical KPI are calculated to assess the performance of a simulated energy system, ie. represent the technical system configuration and operation. They are calculated based on the asset capacities and asset dispatch. They should allow the comparision of different energy system topologies and different project sites with each other. These are the calculated technical KPI:

* :ref:`Aggregated flow <annual_total_flow>`
* :ref:`Average flow <average_flow>`
* :ref:`Degree of Autonomy <degree_of_autonomy>`
* :ref:`Degree of Net Zero Energy <degree_of_nze>`
* :ref:`Dispatch of an asset <flow>`
* :ref:`Onsite energy fraction <onsite_energy_fraction>`
* :ref:`Onsite energy matching <onsite_energy_matching>`
* :ref:`Optimal additional capacity <optimizedAddCap>`
* :ref:`Peak flow <peak_flow>`
* :ref:`Renewable factor <renewable_factor>`
* :ref:`Renewable share of local generation <renewable_share_of_local_generation>`
* :ref:`Energy import <total_consumption_from_energy_provider>`
* :ref:`Energy demand <total_demand>`
* :ref:`Energy excess <total_excess>`
* :ref:`Energy export <total_feedin>`
* :ref:`Total local generation <total_internal_generation>`
* :ref:`Total non-renewable local generation <total_internal_non-renewable_generation>`
* :ref:`Total renewable local generation <total_internal_renewable_generation>`
* :ref:`Total non-renewable energy use <total_non-renewable_energy_use>`
* :ref:`Total renewable energy use <total_renewable_energy_use>`


Economic KPI are calculated to assess the costs of a simulated energy system. They include the costs per asset as well as the system's overall costs. Relative values like the levelized costs of supply allow a comparision to other investment options. These are the calculated economic KPI:

* :ref:`Annual operation, maintenance and dispatch expenses <annuity_om>`
* :ref:`Annuity <annuity_total>`
* :ref:`Costs attributed to a specific sector <attributed_costs>`
* :ref:`Operation and maintenance costs <costs_cost_om>`
* :ref:`Dispatch costs <costs_dispatch>`
* :ref:`Investment costs <costs_investment_over_lifetime>`
* :ref:`Operation, maintenance and dispatch costs <costs_om_total>`
* :ref:`Net Present Costs (NPC) <costs_total>`
* :ref:`Upfront investment costs <costs_upfront_in_year_zero>`
* :ref:`Levelized cost of throughput <levelized_cost_of_energy_of_asset>`
* :ref:`Levelized costs of electricity equivalent <levelized_costs_of_electricity_equivalent>`
* :ref:`Replacement costs <replacement_costs_during_project_lifetime>`


Environmental KPI are calculated to assess the impact of a simulated energy system on the environment. These are the calculated environmental KPI:

* :ref:`Specific GHG per electricity equivalent <specific_emissions_per_electricity_equivalent>`
* :ref:`Total GHG emissions <total_emissions>`

