.. _onsite_energy_fraction:

Onsite energy fraction (onsite_energy_fraction)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Onsite energy fraction is also referred to as self-consumption. It describes the fraction of all locally generated energy that is consumed by the system itself.
:Type: Numeric
:Unit: Factor
:Valid Interval: [0,1]
:Related indicators: :ref:`onsite_energy_matching`

