.. _onsite_energy_matching:

Onsite energy matching (onsite_energy_matching)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: The onsite energy matching is also referred to as self-sufficiency. It describes the fraction of the total demand that can be covered by the locally generated energy.
:Type: Numeric
:Unit: Factor
:Valid Interval: [0,1]
:Related indicators: :ref:`onsite_energy_fraction` | :ref:`total_feedin`

