.. _plot_dispatch:

Dispatch of all assets on a bus
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Visualization of the dispatch of all assets of a specific energy bus, ie. all inflows and outflows of a specific bus. Generated for every single energy bus in the energy system. If relevant, a plot of the state of charge is also displayed.
:Type: Figure
:Unit: kW, kgH2, ...
:Valid Interval: NA
:Related indicators: :ref:`flow`

