.. _renewable_share_of_local_generation:

Renewable share of local generation (renewable_share_of_local_generation)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: The renewable share of local generation describes how much of the energy generated locally is produced from renewable sources. It does not take into account the consumption from energy providers.
:Type: Numeric
:Unit: Factor
:Valid Interval: [0,1]
:Related indicators: :ref:`renewable_factor`

