.. _renewable_factor:

Renewable factor (renewable_factor)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Describes the share of the energy influx to the local energy system that is provided from renewable sources. This includes both local generation as well as consumption from energy providers.
:Type: Numeric
:Unit: Factor
:Valid Interval: [0,1]
:Related indicators: :ref:`renewable_share_of_local_generation` | :ref:`onsite_energy_fraction` | :ref:`onsite_energy_matching`

