.. _specific_emissions_per_electricity_equivalent:

Specific GHG per electricity equivalent (specific_emissions_per_electricity_equivalent)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Specific GHG emissions per supplied electricity equivalent.
:Type: Numeric
:Unit: kg GHGeq/kWh
:Valid Interval: >=0
:Related indicators: :ref:`total_emissions`

