.. _total_non-renewable_energy_use:

Total non-renewable energy use (total_non-renewable_energy_use)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Aggregated amount of non-renewable energy used within the energy system (ie. Including local generation and external supply).
:Type: Numeric
:Unit: kWheleq
:Valid Interval: >=0
:Related indicators: :ref:`total_renewable_energy_use`

