.. _total_internal_renewable_generation:

Total renewable local generation (total_internal_renewable_generation)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:Definition: Aggregated amount of renewable energy generated within the energy system.
:Type: Numeric
:Unit: kWheleq
:Valid Interval: >=0
:Related indicators: :ref:`total_internal_generation` | :ref:`total_internal_non-renewable_generation`

