# Generated by Django 3.1 on 2020-09-01 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EconomicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('currency', models.CharField(choices=[('', 'Choose...'), ('EUR', 'EUR'), ('NOK', 'NOK'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=3)),
                ('discount', models.FloatField()),
                ('tax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('historical_consumption_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConversion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyProduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ESS',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('age_installed', models.FloatField()),
                ('installed_capacity', models.FloatField()),
                ('capex_fix', models.FloatField()),
                ('capex_var', models.FloatField()),
                ('opex_fix', models.FloatField()),
                ('opex_var', models.FloatField()),
                ('lifetime', models.IntegerField()),
                ('optimize_cap', models.BooleanField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('country', models.CharField(choices=[('', 'Choose...'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('Germany', 'Germany'), ('Italy', 'Italy')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('economic_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.economicdata')),
            ],
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('age_installed', models.FloatField()),
                ('installed_capacity', models.FloatField()),
                ('capex_fix', models.FloatField()),
                ('capex_var', models.FloatField()),
                ('opex_fix', models.FloatField()),
                ('opex_var', models.FloatField()),
                ('lifetime', models.IntegerField()),
                ('optimize_cap', models.BooleanField()),
                ('efficiency', models.FloatField()),
                ('soc_initial', models.FloatField()),
                ('soc_max', models.FloatField()),
                ('soc_min', models.FloatField()),
                ('ess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.ess')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChargeController',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('age_installed', models.FloatField()),
                ('installed_capacity', models.FloatField()),
                ('capex_fix', models.FloatField()),
                ('capex_var', models.FloatField()),
                ('opex_fix', models.FloatField()),
                ('opex_var', models.FloatField()),
                ('lifetime', models.IntegerField()),
                ('optimize_cap', models.BooleanField()),
                ('efficiency', models.FloatField()),
                ('ess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.ess')),
                ('start_date', models.DateTimeField()),
                ('period', models.IntegerField()),
                ('time_step', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChargingPower',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('age_installed', models.FloatField()),
                ('installed_capacity', models.FloatField()),
                ('capex_fix', models.FloatField()),
                ('capex_var', models.FloatField()),
                ('opex_fix', models.FloatField()),
                ('opex_var', models.FloatField()),
                ('lifetime', models.IntegerField()),
                ('optimize_cap', models.BooleanField()),
                ('crate', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('self_discharge', models.FloatField()),
                ('ess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.ess')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DischargingPower',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('age_installed', models.FloatField()),
                ('installed_capacity', models.FloatField()),
                ('capex_fix', models.FloatField()),
                ('capex_var', models.FloatField()),
                ('opex_fix', models.FloatField()),
                ('opex_var', models.FloatField()),
                ('lifetime', models.IntegerField()),
                ('optimize_cap', models.BooleanField()),
                ('crate', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('ess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.ess')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WindPlant',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('age_installed', models.FloatField()),
                ('installed_capacity', models.FloatField()),
                ('capex_fix', models.FloatField()),
                ('capex_var', models.FloatField()),
                ('opex_fix', models.FloatField()),
                ('opex_var', models.FloatField()),
                ('lifetime', models.IntegerField()),
                ('optimize_cap', models.BooleanField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.energyproduction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('start_date', models.DateTimeField()),
                ('period', models.IntegerField()),
                ('time_step', models.IntegerField()),
                ('capex_fix', models.FloatField()),
                ('capex_var', models.FloatField()),
                ('opex_fix', models.FloatField()),
                ('opex_var', models.FloatField()),
                ('lifetime', models.IntegerField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='PVPlant',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('age_installed', models.FloatField()),
                ('installed_capacity', models.FloatField()),
                ('capex_fix', models.FloatField()),
                ('capex_var', models.FloatField()),
                ('opex_fix', models.FloatField()),
                ('opex_var', models.FloatField()),
                ('lifetime', models.IntegerField()),
                ('optimize_cap', models.BooleanField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('historical_generation_data', models.TextField()),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.energyproduction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PVInverter',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('age_installed', models.FloatField()),
                ('installed_capacity', models.FloatField()),
                ('capex_fix', models.FloatField()),
                ('capex_var', models.FloatField()),
                ('opex_fix', models.FloatField()),
                ('opex_var', models.FloatField()),
                ('lifetime', models.IntegerField()),
                ('optimize_cap', models.BooleanField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('efficiency', models.FloatField()),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.energyproduction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
