# Generated by Django 3.1 on 2020-09-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200901_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='start_date',
            field=models.DateField(),
        ),
    ]
