# Generated by Django 3.1 on 2020-09-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200904_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacity',
            name='soc_max',
        ),
    ]
