:Name:,:Unit:,:Default:,:Category:,:Restrictions:,:Definition:
Costs for CO2 emission,EUR,None,Financial,,Calculated costs for CO2 emission certificates (current and future) from inputs
LCOE,EUR,None,Financial,0 or above,Levelized costs of energy
Emissions CO2eq,T of CO2eq,None,Environmental,0 or above,"Emissions of CO2eq  (gCO2eq/kWh, TCO2eq emitted)"
Relative emissions CO2eq,Percentage,None,Environmental,0 or above,Emissions of CO2eq relative to another scenario (% reduced emissions compared to another scenario. E.g: BAU)
Investment needed,EUR,None,Financial,0 or above,Total investment needed
Degree of sector-coupling,factor,None,KPI,between 0 and 1,A synergy index of the energy system expressed via the DOA defined in a publication of RLI
Degree of Autonomy (DA),factor,None,KPI,between 0 and 1,"Degree of Autonomy or self sufficiency obtained, typically a number between 0 and 1"
Transformation pathway,None,,Report,,Enable the user to carry out this analysis on how to get from current situation to future situation from the other outputs. The pathway itself shall not be output by the simulation as it depends on policies and human political decisions as well
Scenarios comparisons,None,,Report,,"Comparison of different energy systems  and energy mixs (like RLI stemp-mv tool). Could compare energy savings, costs savings, CO2 savings"
Energy mix,Percentage,None,Technical,,Percentage of each asset for each energy type.
Renewable energy share,Percentage,None,Technical,,The share of renewable energy produced in the output energy mix
Wasted energy,kW,None,Technical,,"Energy which could not be stored, or was lost in Joule effect (heating), i.e. losses in heat boilers"
Installed  capacity,kW,None,Technical,,The minimal capacity that needs to be installed in order to meet peak demand
Installed power,kWh,None,Technical,,The aggregated power that needs to be produced in order to meet demand
Calculate network requirements or expansion possibilities,None,,Report,,Calculate network requirements or expansion possibilities
Grid equipment requirements,,None,Technical,,Number of new transformers (v2.0 of the tool)
Grid cable requirements,km,None,Technical,,length and size of new cables required (v2.0 of the tool)
Available generation technologies,None,,Report,,List of existing technologies which could fulfill the capacity without exceeding the costs
Required storage,kW,None,Technical,,Required size to sustain peak demands for each storage technology (only if storage is part of input)
Connection points,None,,Report,,Transfer interfaces with existing supply structures (gas/electricity/water/wastewater)
Amortisation period of system improvements,Time,None,Financial,0 or above,How many months/years should one wait to get back the money invested in the components/assets
List of support programmes,None,,Report,,"List of support programmes (government, NGO, World Bank) which criteria are fulfilled by the output energy system"
